### ISSUE TITLE
Issue building latest version of OSX version and a question

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#46]
Apologies if this isn't that specific. I just recently downloaded Xcode 7.3.1 and Juce and the latest source for JuceOPLVSTi and I was unable to build the newest version due to an error (unless fixing it uncovers more).

I've successfully built a few test projects in Juce that work in Logic Pro so I know that I can get an audio unit working.

When I build the code I get an Error in the DROMultiplexer.cpp on line 53:

**53 typedef BYTE BOOL;**
"typedef redefinition with different types ('BYTE' (aka 'unsigned char') vs 'signed char')"

I also get several Warnings, one on line 73:

57 void WriteConsole(DWORD conout,const char* strPtr,
                  DWORD count, DWORD* countAdr, int* nul)
...
**73    std::cout << std::endl << msgType << message;**
"Address of function message will always evaluate to 'true'"

And another in line 292:

282 void DROMultiplexer::PercussionChange(Hiopl* opl, int pIdx)
...
**292  for (int i = 0; i < i; i++)**
"Self comparison always evaluates to false"

In any case, I enjoyed playing around with the Mac build, but it did have some issues, namely the sound bug that I put on the wiki where switching JuceOPLVST to a passive channel (selecting another Software Instrument) would trigger some aggressive noise, which is why I'm trying to make a Mac build from the newer version.

------------------------

On an unrelated note, I wanted to ask without being trying to be presumptuous (not asking for an explicit feature request here). Is the goal to eventually have this closer to a "true" OPL3? Right now it's something like an OPL2.5 with 2-OP FM, and 9 voice limitations to simulate the 9 pair/18 OP of the OPL2. However it has the 8 waveforms of the OPL3 vs. the OPL2's 4. 

As far as I'm aware, the only major differences between the OPL3 and OPL2 is the 8 vs. 4 waveforms, double the number of operators (36 vs. 18) and the new 4-OP algorithms, which according to this site: http://www.fit.vutbr.cz/~arnost/opl/opl3.html, only 2 of the 4 produce functionally different sound (the ones he's calling FM-FM and AM-FM Mode). The other two that he calls FM-AM and AM-AM can be recreated on an OPL2 already (and thus JuceOPLVST).

I'm just glad there's some recent attention to the underrated OPL series of chips and would like to help the project in any way I can.

**Comment by bsutherland** [comment]
Hi gdreyband

Thanks for your interest and offer to help!

## OSX

Thanks a lot for trying to build under OSX! If you can get it to build (and it sounds like it's very close, given that there's only one error), I'd really appreciate it if you could submit a pull-request so that I can include it in the repository, and send me the binaries. I know that a lot of other OSX users would be happy too.

As for that error, I think you mean windows.h? It sounds like BOOL is already defined. Perhaps it's been added in a recent XCode version? Anyway, all you should need to do is delete that line and it should build. Please try it and let me know!

Jeff Russ (who originally built it on OSX) added windows.h to provide the required windows typedefs under OSX:

### DROMultiplexer.cpp
```
/// Jeff-Russ added guard against windows.h include if not windows:
#ifdef _WIN32 // covers both 32 and 64-bit
    #include <Windows.h>
#else
    #include "windows.h"
#endif
```

### windows.h
```
///=============================================================================
///    windows.h - as needed re-definition of windows.h functions for non-win
///    Created: 11 Feb 2015 5:08:51pm
///    Author:  Jeff-Russ
///=============================================================================
```

As for the warnings, thanks! I'll fix those.

## OPL2/3

You're right to say it's something like an OPL2.5. The main reason I didn't add the 4-op algorithms is the complexity of the UI. The GUI is already quite large - imagine doubling that. Also, I may be wrong but I don't think 4-op mode was used much in games and software. SBI files only seem to target OPL2 for example. So I'm afraid to say that I don't really have any plans to add support for 4-op modes, or any other features of the OPL3 beyond the extra waveforms.

**Comment by gdreyband** [comment]
You're right, the line was in windows.h I tried removing it (typedef BYTE BOOL), and JUCE gives me this error:

<code>
JIT process crashed!:
Program uses external function 'DBOPL::Chip::Chip()' which could not be resolved.
</code>

After that, Juce can't really recover and attempt compile until restart.

You're right that it does seem close, but I imagine giving instructions to a 3rd party on a different target platform is frustrating, especially since I'm fairly rusty. Just curious, has Jeff Russ been able to build the newer version?

You're right that only recently has there been any sort of resurgence of OPL3 over OPL2 (mostly due to Adlib Tracker or similar). If it ever comes to a point where you're interested , I could help try to create a UI that accommodates the additional operators and algorithms, but I won't belabor the issue.

**Comment by bsutherland** [comment]
I'm happy to help with getting it to compile under OSX.. I'm sure it can't be too far off :)

A quick google of the error message shows that you might be better of building this in XCode rather than in the ProJucer: https://forum.juce.com/t/basic-gui-application-strange-jit-process-crashed-error-in-projucer/17347 

As for new features, I'll certainly consider merging any features you develop back into the project.

**Comment by Jeff-Russ** [comment]
Sorry I've been not responding to this thread: I've been so busy with other things and I've dreaded this being non-trivial and possibly time consuming. To my surprise I downloaded my repo, fired it up Xcode and built it right away with no problems.   
  
I was last able to build for Mac three months ago, which is when my github repo was last updated but for some reason the uploaded built (hosted on google drive - the one with the noise warning and the one linked to from gh-pages) is from February 2015?!? I'm not sure why I didn't upload a new build three months ago. Sorry about that!  
  
Well I've re-uploaded the new builds and they are working fine for me, but I should point out that all of this transpired over a span of about 5 minutes so it's not exactly a thorough evaluation. I'll hopefully have more time in the future for this!   

[download AUi](https://drive.google.com/open?id=0B3RK-KfkucDQMmpBX21scUEtMjg)  
[download VSTi](https://drive.google.com/open?id=0B3RK-KfkucDQZWFlT3YwSEUxaTQ)

**Comment by gdreyband** [comment]
[JuceOPLVSTi.component.zip](https://github.com/bsutherland/JuceOPLVSTi/files/419569/JuceOPLVSTi.component.zip)

Yes! It seems to compile in Xcode just fine, like you said. I've attached it to this issue. Let me know if you need any additional files other than just the component file. As a sidenote, Jeff Russ' AdlibBlaster includes a bunch of SBI files.

I didn't close the issue in case you needed to respond. Otherwise, for the time being the issue is closed. The GUI stuff is unrelated and I will work on it in my spare time and see if I can figure out a way to make it work without making it A) super huge, or B) really confusing.

**Comment by bsutherland** [comment]
Jeff,

Thanks a lot! Really appreciate it as always!

Bruce

**Comment by bsutherland** [comment]
Sorry, just noticed there are still some outstanding issues you mentioned. Please let me know how it goes.

**Comment by gdreyband** [comment]
I'm going to close this one for now. I've noticed that occasionally audio applications cause hard crashes on a Mac, but whatever caused this is a separate issue. It used to happen to me on my old machine if I ever unplugged my Mbox2, so I think it's something to do with core audio. This is the first time it happened to me on this machine but I'll open a new issue if I discover the crash is related to your plugin.

Also the SBI window priority isn't so much a big deal right now, and not worth keeping this issue open over.
