### ISSUE TITLE
Alias-free / bandlimited / oversampled oscillators and processing

### ISSUE THREAD

**Issue by tarocco** [bsutherland/JuceOPLVSTi#62]
It would be really great to hear this VST process high frequencies without the severe aliasing it currently has. I'm able to force my sample rate up to 96000 or even 192000 samples/second in Ableton Live and it sounds much, much better. It would be great to be able to work at 44100 and have the same cleanness to the sound at typical sample rates.

**Comment by bsutherland** [comment]
Hi Tarocco,

This sounds like a great suggestion, but I'll be honest and tell you:

1. I'd have no idea where to begin implementing band-limiting, and only a rudimentary understanding of oversampling at the moment
2. I assume it would require significant changes to the internals of the DOSBox emulation
3. Because of 1 and 2 above, combined with the limited amount of time I have to work on the VST, I'm sorry to say it probably won't happen any time soon

All that said, if you think you're up to the task and have the time to spare, I'd be very open to your contribution :)

In the mean time, as you say, you do have the option of working at high sample rates to improve sound quality.

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, has very high fidelity, and does everything which JuceOPLVSTi does and more. In case you're interested:

https://github.com/jpcima/ADLplug

I'm closing this issue, because I'm sorry to say that I don't plan to enhance JuceOPLVSTi further.
